realease gui v1
cubefs/cubefs-dashboard pull request #1
Opened 2023-07-24 06:18 UTC by wangxiaodong1

[realease gui v1](https://github.com/cubefs/cubefs/pull/2315/commits/c026abb4cf7e2529244d363a87e51668e8c96465)

2023-07-26 02:15 UTC, xiaochunhe requested changes
add a README.md to introduce the basic information and installation process

2023-07-26 02:17 UTC, weilephp commented on frontend/vue.config.js
> +        target: 'http://10.176.204.37:6007',
ip去掉

2023-08-04 08:58 UTC, xiangcai1215 approved these changes
LGTM

2023-08-04 09:07 UTC, hooklee2000 commented
In config.yml  the password of mysql  supports  plain or AES encrypted string.  
Maybe cfs-gui need provide an  -enc parameter to encrypt plain string and print encrypted string?

2023-08-04 09:16 UTC, merged